export const RANK_RULE = {
    RANK_INCREASE_BY_PRICE:'RANK_INCREASE_BY_PRICE',
    RANK_DECREASE_BY_PRICE:'RANK_DECREASE_BY_PRICE',
    RANK_INCREASE_BY_AREA:'RANK_INCREASE_BY_AREA',
    RANK_DECREASE_BY_AREA:'RANK_DECREASE_BY_AREA'
}